steps:
  - id: restoreCache
    name: $_DOCKER_REGISTRY/restore_cache:latest
    args:
      - "--bucket=gs://$_COMPILE_CACHE_BUCKET"
      - "--key=$_IMAGE_NAME-$_BRANCH_NAME"
  - id: buildCompileImage
    waitFor: ["restoreCache"]
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "compile", "-f", "Dockerfile.compile", "."]
  - id: compile
    waitFor: ["buildCompileImage"]
    name: compile
  - id: saveCache
    waitFor: ["compile"]
    name: $_DOCKER_REGISTRY/save_cache:latest
    args:
      - "--bucket=gs://$_COMPILE_CACHE_BUCKET"
      - "--key=$_IMAGE_NAME-$_BRANCH_NAME"
      - "--path=.gradle/caches"
      - "--path=.gradle/wrapper"
  - id: buildSlimImage
    waitFor: ["compile"]
    name: gcr.io/cloud-builders/docker
    args: [
            "build",
            "-t", "$_DOCKER_REGISTRY/$_IMAGE_NAME:$TAG_NAME",
            "-t", "$_DOCKER_REGISTRY/$_IMAGE_NAME:$TAG_NAME-slim",
            "-f", "Dockerfile.slim",
            ".",
          ]
  - id: buildUbuntuImage
    waitFor: ["compile"]
    name: gcr.io/cloud-builders/docker
    args: [
            "build",
            "-t", "$_DOCKER_REGISTRY/$_IMAGE_NAME:$TAG_NAME-ubuntu",
            "-f", "Dockerfile.ubuntu",
            ".",
          ]
  - id: buildJava8Image
    waitFor: ["compile"]
    name: gcr.io/cloud-builders/docker
    args: [
            "build",
            "-t", "$_DOCKER_REGISTRY/$_IMAGE_NAME:$TAG_NAME-java8",
            "-f", "Dockerfile.java8",
            ".",
          ]
  - id: buildUbuntuJava8Image
    waitFor: ["compile"]
    name: gcr.io/cloud-builders/docker
    args: [
            "build",
            "-t", "$_DOCKER_REGISTRY/$_IMAGE_NAME:$TAG_NAME-ubuntu-java8",
            "-f", "Dockerfile.ubuntu-java8",
            ".",
          ]
images:
  - $_DOCKER_REGISTRY/$_IMAGE_NAME:$TAG_NAME
  - $_DOCKER_REGISTRY/$_IMAGE_NAME:$TAG_NAME-slim
  - $_DOCKER_REGISTRY/$_IMAGE_NAME:$TAG_NAME-java8
  - $_DOCKER_REGISTRY/$_IMAGE_NAME:$TAG_NAME-ubuntu
  - $_DOCKER_REGISTRY/$_IMAGE_NAME:$TAG_NAME-ubuntu-java8
timeout: 3600s
options:
  machineType: N1_HIGHCPU_8
substitutions:
  _COMPILE_CACHE_BUCKET: spinnaker-build-cache
